version: '3.8'

services:
  app:
    container_name: nextjs-cv-dev
    build:
      context: .
      dockerfile: Dockerfile.dev
    ports:
      - '3000:3000'
    environment:
      - NODE_ENV=develoement
    volumes:
      - ./:/app
      - /app/node_modules
    restart: unless-stopped
